# Question 1

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.5


In [5]:
np.arange(50)[2:50:3]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [46]:
list1=int(input("Enter size of list"))
print()
numlist=list(int(num)for num in input("Enter list numbers").strip().split())[:list1]
print(" First list: ",numlist)
print()
list2=int(input("Enter size of list"))
print()
numlist2=list(int(num)for num in input("Enter list numbers").strip().split())[:list2]
print()
arr1=np.array(numlist)
arr2=np.array(numlist2)
print("First array converted to numpy array",arr1)
print("Second array converted to numpy array",arr2)
print()

concatenatedArray=np.concatenate((arr1,arr2),axis=0)
print("Concatenated Array: ",concatenatedArray)
print()
concatenatedArray.sort()
print("Sorted Array is: ",concatenatedArray)


Enter size of list5

Enter list numbers1 2 3 4 5
 First list:  [1, 2, 3, 4, 5]

Enter size of list5

Enter list numbers9 8 7 6 5

First array converted to numpy array [1 2 3 4 5]
Second array converted to numpy array [9 8 7 6 5]

Concatenated Array:  [1 2 3 4 5 9 8 7 6 5]

Sorted Array is:  [1 2 3 4 5 5 6 7 8 9]


# Question 3

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The dimension of array is:",arr.ndim)
print("The size of array is:",arr.size)

The dimension of array is: 2
The size of array is: 9


# Question 4

In [13]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print("The array in 1 D is:",arr)
arr2=np.reshape(arr,(2,5))
print("The array in 2 D is:",arr2)

The array in 1 D is: [0 1 2 3 4 5 6 7 8 9]
The array in 2 D is: [[0 1 2 3 4]
 [5 6 7 8 9]]


# Question 5

In [19]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,12,13],[14,15,16],[17,18,19]])
outc=np.vstack((a,b))
outd=np.hstack((a,b))
print(outc)
print(outd)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


# Question 6

In [42]:

def unique(list1): 

 
    unique_list = [] 
    

    for x in list1: 
 
        if x not in unique_list: 
            unique_list.append(x) 
            
    for x in unique_list: 
        print(x) 




list1 = [10, 20, 10, 30, 40, 40] 
print("the unique values from 1st list is") 
unique(list1) 


list2 =[1, 2, 1, 1, 3, 4, 3, 3, 5] 
print("\nthe unique values from 2nd list is") 
unique(list2) 


the unique values from 1st list is
10
20
30
40

the unique values from 2nd list is
1
2
3
4
5
